<?php

/**
 * @file
 * Contains big_pipe_demonstration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function big_pipe_demonstration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the big_pipe_demonstration module.
    case 'help.page.big_pipe_demonstration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Big Pipe demo module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function big_pipe_demonstration_theme() {
  return [
    'big_pipe_demonstration' => [
      'render element' => 'children',
    ],
  ];
}
